services:
    app.menu_builder:
        class: App\Menu\MainMenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: mainMenu, alias: main } # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: sidebarMenu, alias: sidebar } # The alias is what is used to retrieve the menu
