survos_landing: {path: /landing, controller: 'Survos\BaseBundle\Controller\LandingController::landing'}
app_profile: {path: /landing, controller: 'Survos\BaseBundle\Controller\LandingController::landing'}
app_logout: {path: /landing, controller: 'Survos\BaseBundle\Controller\LandingController::landing'}